Repository SOPT-all/36-COLLABORATION-ANDROID-KB-STARBANKING, pull requests merged in 2025-05, with the labels that each got.

#8 setting/#6: 디자인 시스템 컬러 정의
  app/src/main/java/org/sopt/starbanking/ui/theme/Color.kt
  app/src/main/java/org/sopt/starbanking/ui/theme/Theme.kt
Labels: 지현, 🔨 setting

#13 setting/#12: Theme.kt에 Typography 추가
  app/src/main/java/org/sopt/starbanking/ui/theme/Theme.kt
Labels: 지현, 🔨 setting

#14 feature/#10: 버튼 컴포넌트 구현
  app/src/main/java/org/sopt/starbanking/core/components/Button.kt
Labels: 나현, ✨ feature

#15 feature/#11: TopBar 구현
  app/src/main/java/org/sopt/starbanking/core/components/TopBar.kt
  app/src/main/res/drawable/ic_arrow_left.xml
  app/src/main/res/drawable/ic_close.xml
  app/src/main/res/drawable/ic_home.xml
  app/src/main/res/drawable/ic_menu.xml
  app/src/main/res/values/strings.xml
Labels: 지현, ✨ feature

#17 feature/#16: Custom Common Horizontal Divider 구현
  app/src/main/java/org/sopt/starbanking/core/components/.gitkeep
  app/src/main/java/org/sopt/starbanking/core/components/CustomHorizontalDivider.kt
Labels: 세호, ✨ feature

#20 feature/#19 적금 상세 조회 페이지 구현
  app/src/main/java/org/sopt/starbanking/presentation/savingsDetail/SavingsDetailScreen.kt
  app/src/main/java/org/sopt/starbanking/presentation/savingsDetail/SavingsDetailViewModel.kt
  app/src/main/res/drawable/banner_android.xml
  app/src/main/res/drawable/ic_pencil_android.xml
  app/src/main/res/drawable/ic_settings_android.xml
Labels: 나현, ✨ feature, 🎼 compose

#21 feature/#18 계좌 상세 스크린 UI 구현
  app/src/main/java/org/sopt/starbanking/presentation/accountDetail/.gitkeep
  app/src/main/java/org/sopt/starbanking/presentation/accountDetail/AccountDetailScreen.kt
  app/src/main/java/org/sopt/starbanking/presentation/accountDetail/components/AccountDetailDivider.kt
  app/src/main/java/org/sopt/starbanking/presentation/accountDetail/components/AccountDetailMainInfo.kt
  app/src/main/java/org/sopt/starbanking/presentation/accountDetail/components/AccountDetailTitleCard.kt
  app/src/main/java/org/sopt/starbanking/presentation/accountDetail/navigation/AccountDetailNavigation.kt
  app/src/main/java/org/sopt/starbanking/presentation/accountDetail/type/AccountDetailIconType.kt
  app/src/main/java/org/sopt/starbanking/presentation/accountDetail/viewmodel/AccountDetailViewModel.kt
  app/src/main/java/org/sopt/starbanking/presentation/main/MainNavHost.kt
  app/src/main/java/org/sopt/starbanking/presentation/main/MainNavigator.kt
  app/src/main/res/drawable/ic_arrow_down.xml
  app/src/main/res/drawable/ic_arrow_right.xml
Labels: 세호, ✨ feature, 🎼 compose

#23 feature/#22 전체계좌조회 UI 구현
  app/src/main/java/org/sopt/starbanking/core/navigation/RouteModel.kt
  app/src/main/java/org/sopt/starbanking/presentation/allAcounts/AllAccountsScreen.kt
  app/src/main/java/org/sopt/starbanking/presentation/allAcounts/components/AccountCard.kt
  app/src/main/java/org/sopt/starbanking/presentation/allAcounts/components/BusinessAccountShortcut.kt
  app/src/main/java/org/sopt/starbanking/presentation/allAcounts/components/HomeTabMenu.kt
  app/src/main/java/org/sopt/starbanking/presentation/allAcounts/components/SimpleAccordionItem.kt
  app/src/main/java/org/sopt/starbanking/presentation/allAcounts/navigation/AllAccountsNavigation.kt
  app/src/main/java/org/sopt/starbanking/presentation/main/MainNavHost.kt
  app/src/main/java/org/sopt/starbanking/presentation/main/MainNavigator.kt
  app/src/main/res/drawable/ic_arrow_right_android.xml
  app/src/main/res/drawable/ic_card.xml
  app/src/main/res/drawable/ic_menu_vert_android.xml
  app/src/main/res/drawable/ic_order_change.xml
  app/src/main/res/drawable/ic_plus_android.xml
  app/src/main/res/drawable/ic_won.png
Labels: 지현, ✨ feature, 🎼 compose

#25 feature/#24 적금 상세 조회 페이지 API 연동
  app/src/main/java/org/sopt/starbanking/core/components/Button.kt
  app/src/main/java/org/sopt/starbanking/data/dto/base/BaseResponse.kt
  app/src/main/java/org/sopt/starbanking/data/dto/response/ResponseSavingsState.kt
  app/src/main/java/org/sopt/starbanking/data/service/StarBankingService.kt
  app/src/main/java/org/sopt/starbanking/presentation/savingsDetail/SavingsDetailScreen.kt
  app/src/main/java/org/sopt/starbanking/presentation/savingsDetail/SavingsDetailViewModel.kt
Labels: 나현, ✨ feature, 🎼 compose, 🌐 API

#27 feature/#26 계좌이율 스크린 구현
  app/src/main/java/org/sopt/starbanking/core/components/CustomThinDivider.kt
  app/src/main/java/org/sopt/starbanking/presentation/accountDetail/AccountDetailScreen.kt
  app/src/main/java/org/sopt/starbanking/presentation/accountDetail/components/AccountDetailTitleCard.kt
  app/src/main/java/org/sopt/starbanking/presentation/accountInterest/.gitkeep
  app/src/main/java/org/sopt/starbanking/presentation/accountInterest/AccountInterestScreen.kt
  app/src/main/java/org/sopt/starbanking/presentation/accountInterest/components/AccountInterestTable.kt
  app/src/main/java/org/sopt/starbanking/presentation/accountInterest/components/AccountInterestTitle.kt
  app/src/main/java/org/sopt/starbanking/presentation/accountInterest/components/AccountSummary.kt
  app/src/main/java/org/sopt/starbanking/presentation/accountInterest/components/AccountTermInfo.kt
  app/src/main/java/org/sopt/starbanking/presentation/accountInterest/components/NoticeBulletList.kt
  app/src/main/java/org/sopt/starbanking/presentation/accountInterest/components/PreferentialInterestCard.kt
  app/src/main/java/org/sopt/starbanking/presentation/accountInterest/navigation/AccountInterestNavigation.kt
  app/src/main/java/org/sopt/starbanking/presentation/main/MainNavHost.kt
  app/src/main/java/org/sopt/starbanking/presentation/main/MainNavigator.kt
  app/src/main/res/drawable/img_card_1.png
  app/src/main/res/drawable/img_card_2.png
  app/src/main/res/drawable/img_card_3.png
  app/src/main/res/values/strings.xml
Labels: 세호, ✨ feature

#30 feature/#28: 전체계좌조회 api 연결
  app/src/main/java/org/sopt/starbanking/data/dto/response/ResponseTotalAccountState.kt
  app/src/main/java/org/sopt/starbanking/data/service/StarBankingService.kt
  app/src/main/java/org/sopt/starbanking/presentation/allAccount/AllAccountScreen.kt
  app/src/main/java/org/sopt/starbanking/presentation/allAccount/AllAccountViewModel.kt
  app/src/main/java/org/sopt/starbanking/presentation/allAccount/components/AccountCard.kt
  app/src/main/java/org/sopt/starbanking/presentation/allAccount/components/BusinessAccountShortcut.kt
  app/src/main/java/org/sopt/starbanking/presentation/allAccount/components/HomeTabMenu.kt
  app/src/main/java/org/sopt/starbanking/presentation/allAccount/components/SimpleAccordionItem.kt
  app/src/main/java/org/sopt/starbanking/presentation/allAccount/navigation/AllAccountsNavigation.kt
  app/src/main/java/org/sopt/starbanking/presentation/allAcounts/AllAccountsScreen.kt
  app/src/main/java/org/sopt/starbanking/presentation/main/MainNavHost.kt
  app/src/main/java/org/sopt/starbanking/presentation/main/MainNavigator.kt
Labels: 지현, 🌐 API

#33 feature/#32: Jetpack Navigation 연동 끝
  app/src/main/java/org/sopt/starbanking/core/navigation/RouteModel.kt
  app/src/main/java/org/sopt/starbanking/presentation/accountDetail/navigation/AccountDetailNavigation.kt
  app/src/main/java/org/sopt/starbanking/presentation/allAccount/AllAccountScreen.kt
  app/src/main/java/org/sopt/starbanking/presentation/allAccount/components/AccountCard.kt
  app/src/main/java/org/sopt/starbanking/presentation/allAccount/components/SimpleAccordionItem.kt
  app/src/main/java/org/sopt/starbanking/presentation/allAccount/navigation/AllAccountsNavigation.kt
  app/src/main/java/org/sopt/starbanking/presentation/main/MainNavHost.kt
  app/src/main/java/org/sopt/starbanking/presentation/main/MainNavigator.kt
  app/src/main/java/org/sopt/starbanking/presentation/savingsDetail/SavingsDetailScreen.kt
  app/src/main/java/org/sopt/starbanking/presentation/savingsDetail/navigation/SavingDetailNavigation.kt
  app/src/main/java/org/sopt/starbanking/presentation/transactionHistory/.gitkeep
Labels: 세호, ✨ feature
